//! Tests for nix/strip-dev-deps.py — the build-phase script that removes
//! dev-dependency plugins (e.g. integration_test) from the hermetic Flutter
//! build. Leaving them in causes two sandbox failures:
//!   1. The Flutter Gradle plugin resolves each plugin in
//!      .flutter-plugins-dependencies; dev plugins pull deps absent from
//!      pubspec.lock (integration_test -> flutter_driver -> test), and the
//!      resulting pub.dev request dies in the offline sandbox.
//!   2. javac fails on GeneratedPluginRegistrant.java registrations for
//!      plugins excluded from release variants.

use std::path::PathBuf;
use std::process::Command;

fn script_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../nix/strip-dev-deps.py")
}

fn run_script(dir: &std::path::Path, deps: &str, registrant: &str) -> std::process::Output {
    Command::new("python3")
        .arg(script_path())
        .arg(deps)
        .arg(registrant)
        .current_dir(dir)
        .output()
        .expect("python3 must be available to run strip-dev-deps.py")
}

fn deps_json_with_dev_plugin() -> serde_json::Value {
    serde_json::json!({
        "info": "This is a generated file; do not edit or check into version control.",
        "plugins": {
            "ios": [
                {"name": "url_launcher_ios", "path": "/nix/store/aaa/", "native_build": true,
                 "dependencies": [], "dev_dependency": false},
                {"name": "integration_test", "path": "/nix/store/bbb/", "native_build": true,
                 "dependencies": [], "dev_dependency": true}
            ],
            "android": [
                {"name": "url_launcher_android", "path": "/nix/store/ccc/", "native_build": true,
                 "dependencies": [], "dev_dependency": false},
                {"name": "integration_test", "path": "/nix/store/bbb/", "native_build": true,
                 "dependencies": [], "dev_dependency": true}
            ],
            "macos": [],
            "linux": [],
            "windows": [],
            "web": []
        },
        "dependencyGraph": [
            {"name": "integration_test", "dependencies": []},
            {"name": "url_launcher_android", "dependencies": []},
            {"name": "url_launcher_ios", "dependencies": []}
        ],
        "date_created": "1970-01-01 00:00:00.000000",
        "version": "3.44.1"
    })
}

const REGISTRANT_WITH_DEV_PLUGIN: &str = r#"package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  private static final String TAG = "GeneratedPluginRegistrant";
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    try {
      flutterEngine.getPlugins().add(new dev.flutter.plugins.integration_test.IntegrationTestPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin integration_test, dev.flutter.plugins.integration_test.IntegrationTestPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new io.flutter.plugins.urllauncher.UrlLauncherPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin url_launcher_android, io.flutter.plugins.urllauncher.UrlLauncherPlugin", e);
    }
  }
}
"#;

#[test]
fn strips_dev_plugin_from_all_platform_lists() {
    let dir = tempfile::tempdir().unwrap();
    let deps = dir.path().join(".flutter-plugins-dependencies");
    let reg = dir.path().join("GeneratedPluginRegistrant.java");
    std::fs::write(&deps, deps_json_with_dev_plugin().to_string()).unwrap();
    std::fs::write(&reg, REGISTRANT_WITH_DEV_PLUGIN).unwrap();

    let out = run_script(
        dir.path(),
        ".flutter-plugins-dependencies",
        "GeneratedPluginRegistrant.java",
    );
    assert!(
        out.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );

    let result: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&deps).unwrap()).unwrap();
    for platform in ["ios", "android"] {
        let names: Vec<&str> = result["plugins"][platform]
            .as_array()
            .unwrap()
            .iter()
            .map(|p| p["name"].as_str().unwrap())
            .collect();
        assert!(
            !names.contains(&"integration_test"),
            "integration_test must be stripped from {platform}, got {names:?}"
        );
    }
}

#[test]
fn strips_dev_plugin_from_dependency_graph() {
    let dir = tempfile::tempdir().unwrap();
    let deps = dir.path().join(".flutter-plugins-dependencies");
    std::fs::write(&deps, deps_json_with_dev_plugin().to_string()).unwrap();

    let out = run_script(dir.path(), ".flutter-plugins-dependencies", "missing.java");
    assert!(out.status.success());

    let result: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&deps).unwrap()).unwrap();
    let graph: Vec<&str> = result["dependencyGraph"]
        .as_array()
        .unwrap()
        .iter()
        .map(|e| e["name"].as_str().unwrap())
        .collect();
    assert_eq!(graph, vec!["url_launcher_android", "url_launcher_ios"]);
}

#[test]
fn retains_non_dev_plugins() {
    let dir = tempfile::tempdir().unwrap();
    let deps = dir.path().join(".flutter-plugins-dependencies");
    std::fs::write(&deps, deps_json_with_dev_plugin().to_string()).unwrap();

    let out = run_script(dir.path(), ".flutter-plugins-dependencies", "missing.java");
    assert!(out.status.success());

    let result: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&deps).unwrap()).unwrap();
    assert_eq!(
        result["plugins"]["android"][0]["name"], "url_launcher_android",
        "non-dev plugins must survive the strip"
    );
    assert_eq!(result["plugins"]["ios"][0]["name"], "url_launcher_ios");
}

#[test]
fn strips_dev_plugin_registration_from_registrant() {
    let dir = tempfile::tempdir().unwrap();
    let deps = dir.path().join(".flutter-plugins-dependencies");
    let reg = dir.path().join("GeneratedPluginRegistrant.java");
    std::fs::write(&deps, deps_json_with_dev_plugin().to_string()).unwrap();
    std::fs::write(&reg, REGISTRANT_WITH_DEV_PLUGIN).unwrap();

    let out = run_script(
        dir.path(),
        ".flutter-plugins-dependencies",
        "GeneratedPluginRegistrant.java",
    );
    assert!(out.status.success());

    let java = std::fs::read_to_string(&reg).unwrap();
    assert!(
        !java.contains("IntegrationTestPlugin"),
        "integration_test registration must be removed:\n{java}"
    );
    assert!(
        java.contains("UrlLauncherPlugin"),
        "non-dev plugin registration must survive:\n{java}"
    );
}

#[test]
fn exits_cleanly_when_deps_file_missing() {
    let dir = tempfile::tempdir().unwrap();
    let out = run_script(dir.path(), "nonexistent.json", "missing.java");
    assert!(out.status.success(), "missing deps file must be a no-op");
}

#[test]
fn no_dev_deps_leaves_files_untouched() {
    let dir = tempfile::tempdir().unwrap();
    let deps = dir.path().join(".flutter-plugins-dependencies");
    let mut json = deps_json_with_dev_plugin();
    for platform in ["ios", "android"] {
        let plugins = json["plugins"][platform].as_array_mut().unwrap();
        plugins.retain(|p| !p["dev_dependency"].as_bool().unwrap());
    }
    json["dependencyGraph"]
        .as_array_mut()
        .unwrap()
        .retain(|e| e["name"] != "integration_test");
    let original = json.to_string();
    std::fs::write(&deps, &original).unwrap();
    let reg = dir.path().join("GeneratedPluginRegistrant.java");
    std::fs::write(&reg, REGISTRANT_WITH_DEV_PLUGIN).unwrap();

    let out = run_script(
        dir.path(),
        ".flutter-plugins-dependencies",
        "GeneratedPluginRegistrant.java",
    );
    assert!(out.status.success());

    assert_eq!(
        std::fs::read_to_string(&deps).unwrap(),
        original,
        "deps file must be byte-identical when no dev deps exist"
    );
    assert_eq!(
        std::fs::read_to_string(&reg).unwrap(),
        REGISTRANT_WITH_DEV_PLUGIN,
        "registrant must be untouched when no dev deps exist"
    );
}
